/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MockupAlbumRouteImport } from './routes/mockup.album'
import { Route as MockupEventsRouteImport } from './routes/mockup.events'
import { Route as MockupExploreRouteImport } from './routes/mockup.explore'
import { Route as MockupFeedRouteImport } from './routes/mockup.feed'
import { Route as MockupLiveRouteImport } from './routes/mockup.live'
import { Route as MockupMessagesRouteImport } from './routes/mockup.messages'
import { Route as MockupNotificationsRouteImport } from './routes/mockup.notifications'
import { Route as MockupNowPlayingRouteImport } from './routes/mockup.now-playing'
import { Route as MockupProfileRouteImport } from './routes/mockup.profile'
import { Route as MockupSettingsRouteImport } from './routes/mockup.settings'
import { Route as MockupStudioRouteImport } from './routes/mockup.studio'
import { Route as MockupTrackRouteImport } from './routes/mockup.track'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupAlbumRoute = MockupAlbumRouteImport.update({
  id: '/mockup/album',
  path: '/mockup/album',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupEventsRoute = MockupEventsRouteImport.update({
  id: '/mockup/events',
  path: '/mockup/events',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupExploreRoute = MockupExploreRouteImport.update({
  id: '/mockup/explore',
  path: '/mockup/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupFeedRoute = MockupFeedRouteImport.update({
  id: '/mockup/feed',
  path: '/mockup/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupLiveRoute = MockupLiveRouteImport.update({
  id: '/mockup/live',
  path: '/mockup/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupMessagesRoute = MockupMessagesRouteImport.update({
  id: '/mockup/messages',
  path: '/mockup/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupNotificationsRoute = MockupNotificationsRouteImport.update({
  id: '/mockup/notifications',
  path: '/mockup/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupNowPlayingRoute = MockupNowPlayingRouteImport.update({
  id: '/mockup/now-playing',
  path: '/mockup/now-playing',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupProfileRoute = MockupProfileRouteImport.update({
  id: '/mockup/profile',
  path: '/mockup/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupSettingsRoute = MockupSettingsRouteImport.update({
  id: '/mockup/settings',
  path: '/mockup/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupStudioRoute = MockupStudioRouteImport.update({
  id: '/mockup/studio',
  path: '/mockup/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupTrackRoute = MockupTrackRouteImport.update({
  id: '/mockup/track',
  path: '/mockup/track',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mockup/album': typeof MockupAlbumRoute
  '/mockup/events': typeof MockupEventsRoute
  '/mockup/explore': typeof MockupExploreRoute
  '/mockup/feed': typeof MockupFeedRoute
  '/mockup/live': typeof MockupLiveRoute
  '/mockup/messages': typeof MockupMessagesRoute
  '/mockup/notifications': typeof MockupNotificationsRoute
  '/mockup/now-playing': typeof MockupNowPlayingRoute
  '/mockup/profile': typeof MockupProfileRoute
  '/mockup/settings': typeof MockupSettingsRoute
  '/mockup/studio': typeof MockupStudioRoute
  '/mockup/track': typeof MockupTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mockup/album': typeof MockupAlbumRoute
  '/mockup/events': typeof MockupEventsRoute
  '/mockup/explore': typeof MockupExploreRoute
  '/mockup/feed': typeof MockupFeedRoute
  '/mockup/live': typeof MockupLiveRoute
  '/mockup/messages': typeof MockupMessagesRoute
  '/mockup/notifications': typeof MockupNotificationsRoute
  '/mockup/now-playing': typeof MockupNowPlayingRoute
  '/mockup/profile': typeof MockupProfileRoute
  '/mockup/settings': typeof MockupSettingsRoute
  '/mockup/studio': typeof MockupStudioRoute
  '/mockup/track': typeof MockupTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mockup/album': typeof MockupAlbumRoute
  '/mockup/events': typeof MockupEventsRoute
  '/mockup/explore': typeof MockupExploreRoute
  '/mockup/feed': typeof MockupFeedRoute
  '/mockup/live': typeof MockupLiveRoute
  '/mockup/messages': typeof MockupMessagesRoute
  '/mockup/notifications': typeof MockupNotificationsRoute
  '/mockup/now-playing': typeof MockupNowPlayingRoute
  '/mockup/profile': typeof MockupProfileRoute
  '/mockup/settings': typeof MockupSettingsRoute
  '/mockup/studio': typeof MockupStudioRoute
  '/mockup/track': typeof MockupTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mockup/album'
    | '/mockup/events'
    | '/mockup/explore'
    | '/mockup/feed'
    | '/mockup/live'
    | '/mockup/messages'
    | '/mockup/notifications'
    | '/mockup/now-playing'
    | '/mockup/profile'
    | '/mockup/settings'
    | '/mockup/studio'
    | '/mockup/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mockup/album'
    | '/mockup/events'
    | '/mockup/explore'
    | '/mockup/feed'
    | '/mockup/live'
    | '/mockup/messages'
    | '/mockup/notifications'
    | '/mockup/now-playing'
    | '/mockup/profile'
    | '/mockup/settings'
    | '/mockup/studio'
    | '/mockup/track'
  id:
    | '__root__'
    | '/'
    | '/mockup/album'
    | '/mockup/events'
    | '/mockup/explore'
    | '/mockup/feed'
    | '/mockup/live'
    | '/mockup/messages'
    | '/mockup/notifications'
    | '/mockup/now-playing'
    | '/mockup/profile'
    | '/mockup/settings'
    | '/mockup/studio'
    | '/mockup/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MockupAlbumRoute: typeof MockupAlbumRoute
  MockupEventsRoute: typeof MockupEventsRoute
  MockupExploreRoute: typeof MockupExploreRoute
  MockupFeedRoute: typeof MockupFeedRoute
  MockupLiveRoute: typeof MockupLiveRoute
  MockupMessagesRoute: typeof MockupMessagesRoute
  MockupNotificationsRoute: typeof MockupNotificationsRoute
  MockupNowPlayingRoute: typeof MockupNowPlayingRoute
  MockupProfileRoute: typeof MockupProfileRoute
  MockupSettingsRoute: typeof MockupSettingsRoute
  MockupStudioRoute: typeof MockupStudioRoute
  MockupTrackRoute: typeof MockupTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup/album': {
      id: '/mockup/album'
      path: '/mockup/album'
      fullPath: '/mockup/album'
      preLoaderRoute: typeof MockupAlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup/events': {
      id: '/mockup/events'
      path: '/mockup/events'
      fullPath: '/mockup/events'
      preLoaderRoute: typeof MockupEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup/explore': {
      id: '/mockup/explore'
      path: '/mockup/explore'
      fullPath: '/mockup/explore'
      preLoaderRoute: typeof MockupExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup/feed': {
      id: '/mockup/feed'
      path: '/mockup/feed'
      fullPath: '/mockup/feed'
      preLoaderRoute: typeof MockupFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup/live': {
      id: '/mockup/live'
      path: '/mockup/live'
      fullPath: '/mockup/live'
      preLoaderRoute: typeof MockupLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup/messages': {
      id: '/mockup/messages'
      path: '/mockup/messages'
      fullPath: '/mockup/messages'
      preLoaderRoute: typeof MockupMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup/notifications': {
      id: '/mockup/notifications'
      path: '/mockup/notifications'
      fullPath: '/mockup/notifications'
      preLoaderRoute: typeof MockupNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup/now-playing': {
      id: '/mockup/now-playing'
      path: '/mockup/now-playing'
      fullPath: '/mockup/now-playing'
      preLoaderRoute: typeof MockupNowPlayingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup/profile': {
      id: '/mockup/profile'
      path: '/mockup/profile'
      fullPath: '/mockup/profile'
      preLoaderRoute: typeof MockupProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup/settings': {
      id: '/mockup/settings'
      path: '/mockup/settings'
      fullPath: '/mockup/settings'
      preLoaderRoute: typeof MockupSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup/studio': {
      id: '/mockup/studio'
      path: '/mockup/studio'
      fullPath: '/mockup/studio'
      preLoaderRoute: typeof MockupStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup/track': {
      id: '/mockup/track'
      path: '/mockup/track'
      fullPath: '/mockup/track'
      preLoaderRoute: typeof MockupTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MockupAlbumRoute: MockupAlbumRoute,
  MockupEventsRoute: MockupEventsRoute,
  MockupExploreRoute: MockupExploreRoute,
  MockupFeedRoute: MockupFeedRoute,
  MockupLiveRoute: MockupLiveRoute,
  MockupMessagesRoute: MockupMessagesRoute,
  MockupNotificationsRoute: MockupNotificationsRoute,
  MockupNowPlayingRoute: MockupNowPlayingRoute,
  MockupProfileRoute: MockupProfileRoute,
  MockupSettingsRoute: MockupSettingsRoute,
  MockupStudioRoute: MockupStudioRoute,
  MockupTrackRoute: MockupTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
